var config = [
	{
		navigation:'名站导航内容',
		list:[
			{
				name:'Google',
				href:'http://www.google.com.hk',
				title:'Google'				
			},
			{
				name:'百度',
				href:'http://www.baidu.com/',
				title:'百度'				
			},
			{
				name:'网易',
				href:'http://www.163.com/',
				title:'网易'				
			},
			{
				name:'搜狐',
				href:'http://www.sohu.com/',
				title:'搜狐'				
			},
			{
				name:'腾讯',
				href:'http://www.qq.com',
				title:'腾讯'				
			},
			{
				name:'360安全中心',
				href:'http://www.360.com/',
				title:'360安全中心'

			},
			{
				name:'新浪',
				href:'http://www.sina.com.cn',
				title:'新浪'
			},
			{
				name:'雅虎中国',
				href:'http://cn.yahoo.com/',
				title:'雅虎中国'
			},
			{
				name:'VeryCD',
				href:'http://www.verycd.com/',
				title:'VeryCD'
			},
			{
				name:'中华网',
				href:'http://www.china.com/',
				title:'中华网'
			},
			{
				name:'凤凰网',
				href:'http://www.ifeng.com/',
				title:'凤凰网'
			},
			{
				name:'人力资源网',
				href:'http://www.hr.com.cn/',
				title:'人力资源网'
			},
			{
				name:'中国天气',
				href:'http://www.weather.com.cn/',
				title:'中国天气'
			},
			{
				name:'21CN',
				href:'http://it.21cn.com/',
				title:'21CN'
			},
			{
				name:'MSDN中国',
				href:'http://msdn.microsoft.com/zh-cn/default.aspx',
				title:'MSDN中国'
			}

		]

	},
	{
		navigation:'IT资讯',
		list:[
			{
				name:'IT人网',
				href:'http://www.itren.cn/',
				title:'IT人网'				
			},
			{
				name:'PC泡泡网',
				href:'http://www.pcpop.com/',
				title:'PC泡泡网'
			},
			{
				name:'IT168',
				href:'http://www.it168.com/',
				title:'IT168'
			},
			{
				name:'天极网(IT消费)',
				href:'http://www.yesky.com/',
				title:'天极网(IT消费)'
			},
			{
				name:'TOM科技',
				href:'http://tech.tom.com/',
				title:'TOM科技'
			},
			{
				name:'IT部落',
				href:'http://www.itbulo.com/',
				title:'IT部落'
			},
			{
				name:'IT时代周刊',
				href:'ttp://www.ittime.com.cn/',
				title:'IT时代周刊'
			},
			{
				name:'IT人脉圈',
				href:'http://ren.docools.com/',
				title:'IT人脉圈'
			},
			{
				name:'IT公司面试',
				href:'http://www.mianwww.com/',
				title:'IT公司面试'
			}
			]	

	},
	{
		navigation:'网上商城',
		list:[
			{
				name:'雅客网',
				href:'http://www.yoka.com/',
				title:'雅客网'				
			},
			{
				name:'当当网',
				href:'http://www.dangdang.com/',
				title:'当当网'
			},
			{
				name:'天猫',
				href:'https://www.tmall.com/',
				title:'天猫'
			},
			{
				name:'淘宝网',
				href:'http://www.taobao.com/',
				title:'淘宝网'
			},
			{
				name:'卓越亚马逊',
				href:'http://www.amazon.cn/',
				title:'卓越亚马逊'
			},
			{
				name:'上海第一书城',
				href:'http://www.1-book.cn/',
				title:'上海第一书城'
			},
			{
				name:'易趣网',
				href:'http://www.eachnet.com/',
				title:'易趣网'
			},
			{
				name:'IT时代周刊',
				href:'ttp://www.ittime.com.cn/',
				title:'IT时代周刊'
			},
			{
				name:'糯米网',
				href:'http://www.nuomi.com/',
				title:'糯米网'
			},
			{
				name:'聚美优品',
				href:'http://gz.jumei.com/',
				title:'聚美优品'
			}
			,
			{
				name:'1号店',
				href:'http://www.yhd.com/',
				title:'1号店'
			},
			{
				name:'乐淘鞋',
				href:'http://www.letao.com/',
				title:'乐淘鞋'
			},
			{
				name:'唯品会',
				href:'http://www.vip.com/',
				title:'唯品会'
			},
			{
				name:'苏宁易购',
				href:'http://www.suning.com/',
				title:'苏宁易购'
			},
			{
				name:'京东',
				href:'https://www.jd.com/',
				title:'京东'
			},
			{
				name:'国美在线',
				href:'http://www.gome.com.cn/',
				title:'国美在线'
			},
			{
				name:'蘑菇街',
				href:'http://www.mogujie.com/',
				title:'蘑菇街'
			},
			{
				name:'美丽说',
				href:'http://www.meilishuo.com/',
				title:'美丽说'
			}
			]	

	},
	{
		navigation:' WEB前端个人博客',
		list:[
			{
				name:"鑫空间",
				href:"http://www.zhangxinxu.com/",
				title:"鑫空间"
			},
			{
				name:"小志个人博客",
				href:"http://blog.ddnxz.cn/",
				title:"小志个人博客"
			},
			{
				name:"落单的孤鸟",
				href:"http://blog.sjxyz.cn/",
				title:"落单的孤鸟"
			},
			{
				name:"99css",
				href:"http://www.99css.com/",
				title:"99css"
			},
			{
				name:"向东而立",
				href:"http://www.cndong.cn/",
				title:"向东而立"
			},
			{
				name:"jovey",
				href:"http://www.jovey.net/blog/",
				title:"jovey"
			},
			{
				name:"维奇前端观察",
				href:"http://www.cnblogs.com/wiky/",
				title:"维奇前端观察"
			},
			{
				name:"子鼠前端",
				href:"http://www.zishu.cn/",
				title:"子鼠前端"
			},
			{
				name:"阿当",
				href:"http://www.adanghome.com/",
				title:"阿当"
			}
		]
	},
	{
		navigation:'书吧',
		list:[
			{
				name:'看书啦',
				href:'http://www.kanshula.com.cn/',
				title:'看书啦'				
			},
			{
				name:'古典文学',
				href:'http://www.dakuai.com/',
				title:'古典文学'				
			},
			{
				name:'诗文天下',
				href:'http://www.shi-wen.com/',
				title:'诗文天下'				
			},
			{
				name:'意林网',
				href:'http://www.yiddn.net.cn',
				title:'意林网'				
			},
			{
				name:'丁香园',
				href:'http://www.dxy.cn',
				title:'丁香园'				
			},
			{
				name:'国家地理',
				href:'http://www.didd360.com',
				title:'国家地理'				
			},
			{
				name:'华夏地理',
				href:'http://ngmchina.com.cn/',
				title:'华夏地理'				
			},
			{
				name:'经典散文网',
				href:'http://www.jdsanwen.cn',
				title:'经典散文网'				
			},
			{
				name:'青年文摘',
				href:'http://www.qnwz.cn',
				title:'青年文摘'				
			},
			{
				name:'乐读网',
				href:'http://www.ledu365.com',
				title:'乐读网'				
			},
			{
				name:'计算机文摘',
				href:'http://www.pcdigest.com/',
				title:'计算机文摘'				
			},
			{
				name:'读者',
				href:'http://www.duzhe.com/',
				title:'读者'				
			},
			{
				name:'中华诗词网',
				href:'http://www.zhsc.net',
				title:'中华诗词网'				
			},
			{
				name:'中华军事',
				href:'http://middtary.china.com/',
				title:'中华军事'				
			}
		]

	},
	{
		navigation:'Web前端',
		list:[
			{
				name:'一流素材网',
				href:'http://www.16sucai.com/',
				title:'一流素材网'				
			},
			{
				name:'w3school',
				href:'http://www.w3school.com.cn',
				title:'w3school'				
			},
			{
				name:'html中文站',
				href:'http://www.houoop.com/',
				title:'html中文站'				
			},
			{
				name:'html5画廊',
				href:'http://html5gallery.com/',
				title:'html5画廊'				
			},
			{
				name:'阿里西西',
				href:'http://www.alixixi.com/',
				title:'阿里西西'				
			},
			{
				name:'CSS布局',
				href:'http://www.mycelly.com/',
				title:'CSS布局'				
			},
			{
				name:'牛图库',
				href:'http://js.niutuku.com/',
				title:'牛图库'				
			},
			{
				name:'UCD中国',
				href:'http://ucdchina.com/',
				title:'UCD中国'				
			},
			{
				name:'web设计墙',
				href:'http://www.webdesignerwall.com/',
				title:'web设计墙'				
			},
			{
				name:'seo研究中心',
				href:'http://www.moonseo.cn/',
				title:'seo研究中心'				
			},
			{
				name:'我烧网',
				href:'http://woshao.com/',
				title:'我烧网'				
			},
			{
				name:'js菜鸟吧',
				href:'http://www.mb5u.com/divcssjiaocheng/',
				title:'js菜鸟吧'				
			}
			,

			{
				name:'中国设计秀',
				href:'http://www.cnwebshow.com/',
				title:'中国设计秀'				
			},

			{
				name:'中国IDC圈',
				href:'http://www.idcquan.com/',
				title:'中国IDC圈'				
			},

			{
				name:'网页大本营',
				href:'http://www.code-123.com/',
				title:'网页大本营'				
			},

			{
				name:'web一起学',
				href:'http://www.w17x.com/',
				title:'web一起学'				
			},

			{
				name:'web站长站',
				href:'http://www.itokit.com/',
				title:'web站长站'				
			},

			{
				name:'CSScddp',
				href:'http://www.csscddp.com/',
				title:'CSScddp'				
			},

			{
				name:'Web3D中文站',
				href:'http://www.web3d.com.cn/',
				title:'Web3D中文站'				
			},

			{
				name:'web站长站',
				href:'http://www.itokit.com/',
				title:'web站长站'				
			},

			{
				name:'顶尖设计',
				href:'http://www.bobd.cn/',
				title:'顶尖设计'				
			},

			{
				name:'CSS学习网',
				href:'http://www.cssxuexi.com/',
				title:'CSS学习网'				
			},

			{
				name:'设计前沿',
				href:'http://www.foreidea.com/',
				title:'设计前沿'				
			},

			{
				name:'CSS88',
				href:'http://www.css88.com/',
				title:'CSS88'				
			},

			{
				name:'前端观察',
				href:'http://www.qianduan.net/',
				title:'前端观察'				
			},

			{
				name:'淘宝UED',
				href:'http://ued.taobao.com/blog/',
				title:'淘宝UED'				
			},

			{
				name:'前沿视频教室',
				href:'http://learning.artech.cn/',
				title:'前沿视频教室'				
			},

			{
				name:'Aptana',
				href:'http://www.aptana.org/',
				title:'Aptana'				
			},

			{
				name:'jQuery官网',
				href:'http://jquery.com/',
				title:'jQuery官网'				
			},

			{
				name:'jQueryAjax',
				href:'http://www.jqueryajax.com/',
				title:'jQueryAjax'				
			},

			{
				name:'jQuery中文社区',
				href:'http://bbs.jquery.org.cn',
				title:'jQuery中文社区'				
			},

			{
				name:'365css',
				href:'http://www.365css.cn/',
				title:'365css'				
			},

			{
				name:'CSS3_html5',
				href:'http://www.css3-html5.com/',
				title:'CSS3_html5'				
			},

			{
				name:'CSS3info',
				href:'http://www.css3.info/',
				title:'CSS3info'				
			}
			,

			{
				name:'前端开发',
				href:'http://www.wxwdesign.cn/',
				title:'前端开发'				
			}
			,
			{
				name:"前端网",
				href:"http://www.w3cfuns.com/",
				title:"前端网"

			},
			{
				name:'中国站长',
				href:'http://down.cnzz.cn/',
				title:'中国站长'				
			}
			,

			{
				name:'jquery插件',
				href:'http://jquery.malsup.com/',
				title:'jquery插件'				
			}
		]

	},
	{
		navigation:'英语学习',
		list:[
			{
				name:'爱词霸',
				href:'http://www.iciba.com/',
				title:'爱词霸'				
			},
			{
				name:'中国英语网',
				href:'http://www.chinaengddsh.com.cn/',
				title:'中国英语网'				
			},
			{
				name:'英语沙龙',
				href:'http://www.es123.com/',
				title:'英语沙龙'				
			},
			{
				name:'沪江网',
				href:'http://class.hujiang.com/',
				title:'沪江网'				
			},
			
			{
				name:'n词酷',
				href:'http://www.nciku.com/',
				title:'n词酷'				
			},
			{
				name:'百度词典',
				href:'http://dict.baidu.com/',
				title:'百度词典'				
			},
			{
				name:'有道词典',
				href:'http://dict.youdao.com/',
				title:'有道词典'				
			},
			{
				name:'无忧考网',
				href:'http://www.51test.net/',
				title:'无忧考网'				
			},
			{
				name:'英语学习论坛',
				href:'http://bbs.24en.com/',
				title:'英语学习论坛'				
			},
			{
				name:'大耳朵英语',
				href:'http://www.bigear.cn/',
				title:'大耳朵英语'				
			},
			{
				name:'爱思英语',
				href:'http://www.24en.com/',
				title:'爱思英语'				
			}
		]

	},
	{
		navigation:'UED大全',
		list:[
			{
				name:'搜狐UED',
				href:'http://ued.sohu.com/',
				title:'搜狐UED'				
			},
			{
				name:'淘宝UED',
				href:'http://ued.taobao.com/',
				title:'淘宝UED'				
			},
			{
				name:'网易UED',
				href:'http://www.ued163.com/',
				title:'网易UED'				
			},
			{
				name:'携程UED',
				href:'http://ued.ctrip.com/',
				title:'携程UED'				
			},
			
			{
				name:'人人网FED',
				href:'http://fed.renren.com/',
				title:'人人网FED'				
			},
			{
				name:'腾讯ISD',
				href:'http://isd.tencent.com/',
				title:'腾讯ISD'				
			},
			{
				name:'支付宝UED',
				href:'http://ued.alipay.com/',
				title:'支付宝UED'				
			},
			{
				name:'盛大UED',
				href:'http://www.sndaued.com/',
				title:'盛大UED'				
			}
		]

	},
	{
		navigation:'找工作',
		list:[
			{
				name:'51Job',
				href:'http://www.51job.com/',
				title:'51Job'				
			},
			{
				name:'中华英才网',
				href:'http://www.chinahr.com/index.htm',
				title:'中华英才网'				
			},
			{
				name:'智联招聘',
				href:'http://www.zhaopin.com/',
				title:'智联招聘'				
			},
			
			{
				name:'中国海峡人才网',
				href:'http://www.hxrc.com/',
				title:'中国海峡人才网'				
			}
		]

	}


]